apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: rhbk
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres
    usernameSecret:
      name: postgres-credentials
      key: username
    passwordSecret:
      name: postgres-credentials
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
    strictBackchannel: false
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: features
      value: preview
    - name: log-level
      value: INFO