apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: kuadrant-system
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: news-api
stringData:
  api_key: "secret-key-12345"
type: Opaque